version: '3.8'

services:
  webserver:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    environment:
      DB_HOST: db
      DB_DATABASE: biblioteca
      DB_USERNAME: crud_user
      DB_PASSWORD: senha_da_nasa
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 300M

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: senha_da_nasa_root
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: crud_user
      MYSQL_PASSWORD: senha_da_nasa
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: senha_da_nasa_root
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M

volumes:
  dbdata:
