version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.1' # 1 core

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: biblioteca # Certifique-se de que este nome está correto
      MYSQL_USER: user
      MYSQL_PASSWORD: senha_da_nasa # Deve ser a mesma senha que você usar no PHP
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql # Mapeando seu arquivo init.sql
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.1' # 1 core

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db # Nome do serviço do MySQL
      PMA_USER: user # Altere para o usuário se necessário
      PMA_PASSWORD: senha_da_nasa # Senha correspondente
    depends_on:
      - db
