

services:
  webserver:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    environment:
      DB_HOST: db
      DB_DATABASE: biblioteca
      DB_USERNAME: crud_user
      DB_PASSWORD: senha_da_nasa
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 300M
    entrypoint: sh -c "sleep 30 && apache2-foreground" # Espera 30 segundos antes de iniciar o Apache

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senha_da_nasa_root
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: crud_user
      MYSQL_PASSWORD: senha_da_nasa
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: senha_da_nasa_root
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 200M

volumes:
  dbdata:
