
services:
  web:
    build: .
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: "1.0"
    depends_on:
      - db
    networks:
      - my_network
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: senha_da_nasa
      MYSQL_DATABASE: biblioteca
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: "1.0"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psenha_da_nasa"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: senha_da_nasa
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: "0.5"
        reservations:
          cpus: "0.25"
    depends_on:
      - db
    networks:
      - my_network
    restart: always

volumes:
  db_data:

networks:
  my_network:
